### Import Parameters
importParameters:
  createSpaces: true
  createIndicators: true
  createRecords: true

### CSV Configuration
separator: "" 

### Source Files
sources:
  inputFolder: "DataLifting_input"

### Property Mappings
mapping_spaces:
  hasSpaceType: "spaceType"
  hasSpaceID: "ID"
  hasName: "name"

  hasParentSpaceID: "hasParentSpaceID"
  hasPopulation: ""
  hasCentroidLatitude: ""
  hasCentroidLongitude: ""
  hasSqmArea: ""

  contains: ""


mapping_indicators:
  hasIndicatorType: "indicatorType"
  hasObject: "object"
  onTerritoryName: "territoryName"
  onTerritorySpaceID: "territorySpaceID"
  hasCalculationMethod: "calculationMethod"

  hasNumerator: ""
  hasDenominator: ""
  hasExpression: "hasExpression"
  hasPlainTextDescription: ""

  hasTripPurposeTheme: ""
  hasTransportationModeTheme: ""
  
  hasTerritories: ""
  hasRecords: "IndicatorsRecords"


mapping_records:

  onSpatialLocationID: "code"
  onSpatialLocationName: "name"

  onOriginID: ""
  onOriginName: ""
  onDestinationID: ""
  onDestinationName: ""

  hasStartTime: ""
  hasEndTime: ""

  hasTripPurpose: ""
  hasTransportationMode: ""
  hasPopulationProfile: ""

  hasValue: "value"

  linkedIndicatorType: ""
  linkedObject: ""
  linkedCalculationMethod: ""
  linkedIndicatorTerritoryName: ""
  linkedIndicatorTerritorySpaceID: ""


mapping_geometries:

  hasAssociatedSpaceID: "code"
  hasAssociatedName: "name"

  hasCentroidLatitude: "hasCentroidLatitude"
  hasCentroidLongitude: "hasCentroidLongitude"
  hasSqmArea: "sqm"