# Modified by Inria - WIMMICS team on 12/08/2026
# (Author: Jean Vrignaud - Intern)
# 
# Original work Copyright [2012-2013] Ontology Engineering Group, Universidad Politécnica de Madrid, Spain
# Licensed under the Apache License, Version 2.0

version: '3.2'
services:

  morph-xr2rml:
    image: frmichel/morph-xr2rml:v1.3.2
    container_name: morph-xr2rml
    networks:
      - xr2rml-net
    volumes:
      - "./DataLifting_mappings:/xr2rml_config"
      - "./DataLifting_output:/xr2rml_output"
      - "./log:/log"

  mongo-xr2rml:
    image: mongo:4.4.6
    container_name: mongo-xr2rml    
    networks:
      - xr2rml-net
    ports:
      - "27017:27017"
    volumes:
      - "./mongo_db:/data/db"
      - "./mongo_tools:/mongo_tools"
      - "./DataLifting_intermediateFiles:/mongo_import"

  virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    container_name: virtuoso-server
    networks:
      - xr2rml-net
    environment:
      - DBA_PASSWORD=mysecret 
      - SPARQL_UPDATE=true
    ports:
      - "8890:8890" 
      - "1111:1111" 
    volumes:
      - "./virtuoso_db:/database"
      - "./DataLifting_output:/usr/share/proj" 

networks:
  xr2rml-net:
    driver: bridge
